---
templatelink: "https://raw.githubusercontent.com/appuio/openshift-ansible-contrib/37/reference-architecture/azure-ansible/3.7/azuredeploy.json"
numberofnodes: 3
image: "rhel"
mastervmsize: "Standard_DS4_v2"
infranodesize: "Standard_DS4_v2"
nodevmsize: "Standard_DS4_v2"
location: "westus"
openshiftsdn: "redhat/openshift-ovs-multitenant"
metrics: true
logging: true
opslogging: false
